const express = require("express");
const router = express.Router();
const PojectRoutes = require("./Project/project.routes.js");
const ProjectWorkflowRoutes = require("./Project/project.workflow.routes.js");
const UserRoutes = require("./User/user.routes.js");
const TeamRoutes = require("./Team/team.route.js");
const TeamMemberRoutes = require("./Team/team.member.routes.js");
const WorkspaceRoutes = require("./WorkSpace/workspace.routes.js");
const SprintRoutes = require("./Sprint/sprint.routes.js");
const SprintWorkflowRoutes = require("./Sprint/sprint.workflow.routes.js");
const protect = require(".././middleware/auth.middleware.js");
const taskRoutes = require("./Task/task.routes.js");
const commentRoutes = require("./Comment/comment.routes.js");
const labelRoutes = require("./Label/label.routes.js");
const notificationRoutes = require("./Notification/notification.routes.js");
const chatRoutes = require("./Chat/chat.routes.js");
const messageRoutes = require("./Message/message.routes.js");
const attachmentRoutes = require("./Attachment/attachment.routes.js");
const workspaceMemberRoutes = require("./WorkSpace/workspace.member.routes.js");
const teamMemberRoutes = require("./Team/team.member.routes.js");
const taskWorkflowRoutes = require("./Task/task.workflow.routes.js");
const activityRoutes = require("./activity.route.js");
const searchRoutes = require("./Search/search.route.js");
const settingsRoutes = require("./Settings/settings.routes.js");

///// user routes first to log in to get token and then access other routes
router.use("/users", UserRoutes);
router.use(protect);
router.use("/workspace", WorkspaceRoutes);
router.use("/", PojectRoutes);
router.use("/", TeamRoutes);
router.use("/", TeamMemberRoutes);
router.use("/", SprintRoutes);
router.use("/", SprintWorkflowRoutes);
router.use("/", taskRoutes);
router.use("/", commentRoutes);
router.use("/", labelRoutes);
router.use("/", notificationRoutes);
router.use("/", chatRoutes);
router.use("/", messageRoutes);
router.use("/", attachmentRoutes);
router.use("/", workspaceMemberRoutes);
router.use("/", teamMemberRoutes);
router.use("/", taskWorkflowRoutes);
router.use("/", ProjectWorkflowRoutes);
router.use("/", activityRoutes);
router.use("/", searchRoutes);
router.use("/settings", settingsRoutes);
module.exports = router;
